# Stage 1: Build the JAR using Maven
FROM maven:3.8-openjdk-11 AS build
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN mvn clean package -DskipTests

# Stage 2: Run the JAR using your OpenShift Runtime
FROM default-route-openshift-image-registry.apps.rm2.thpm.p1.openshiftapps.com/openshift/java-runtime:openjdk-11-ubi8
COPY --from=build /usr/src/app/target/*.jar /deployments/app.jar
CMD ["java", "-jar", "/deployments/app.jar"]